# Copyright 2025 by David Weikersdorfer
[workspace]
resolver = "2"
members = [
  "crates/*", "flecs_toybox", "toybox",
]

[workspace.dependencies]
bincode = { version = "2.0", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4.7"
env_logger = { version = "0.11" }
eyre = "0.6"
approx = "0.5.1"
flecs_ecs = { git = "https://github.com/Indra-db/Flecs-Rust.git", branch = "main", features = ["flecs_module", "flecs_system", "flecs_manual_registration"] }
rust_decimal = { version = "1.37.2", features = ["macros", "maths"] }
rust_decimal_macros = { version = "1.37.1", features = ["reexportable"] }
gems = { path = "crates/gems" }
gos_common = { path = "crates/gos_common" }
gosim = { path = "crates/gosim" }
log = "0.4"
nng = "1.0"
paste = "1.0.15"
prost = "0.13"
prost-build = "0.13"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slab = "0.4"
snap = "1.1"
steamworks = "0.12.0"
thiserror = "1.0"
typenum = "1.18.0"
ratatui = "0.29.0"
tui-popup = "0.6.0"
uom = "0.37.0"
