# Copyright 2025 by David Weikersdorfer
[workspace]
resolver = "2"
members = [
  "crates/*",
  #"toybox",
]
exclude = ["crates/goscl", "crates/gosrv"]

[profile.dev]
debug = true

[workspace.dependencies]
approx = "0.5.1"
bincode = { version = "2.0", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4.7"
env_logger = { version = "0.11" }
excess = { path = "I:/Ikabur/atom/crates/excess" }
excess_macros = { path = "I:/Ikabur/atom/crates/excess_macros" }
eyre = "0.6"
flowsim = { path = "crates/flowsim" }
gems = { path = "crates/gems" }
gos_common = { path = "crates/gos_common" }
gosim = { path = "crates/gosim" }
log = "0.4"
mocca = { path = "I:/Ikabur/atom/crates/mocca" }
nalgebra = "0.34.0"
nng = "1.0"
num-traits = "0.2.19"
paste = "1.0.15"
prost = "0.13"
prost-build = "0.13"
ratatui = "0.29.0"
rust_decimal = { version = "1.37.2", features = ["macros", "maths"] }
rust_decimal_macros = { version = "1.37.1", features = ["reexportable"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplecs = { path = "I:/Ikabur/atom/crates/simplecs" }
slab = "0.4"
snap = "1.1"
steamworks = "0.12.0"
thiserror = "1.0"
tui-popup = "0.6.0"
typenum = "1.18.0"
